name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Install Chrome Browser
        run: npx playwright install chromium
      - name: Run Playwright tests
        id: test
        run: npx playwright test
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: ${{ !failure() && steps.test.outcome != 'failure' }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  download_artifact: 
    needs: test
    uses: ./.github/workflows/reusable.yml
    with:
      artifact_name: playwright-report
      path: playwright-report/
